### ISSUE TITLE
Handle spaces in influxdb measurement names

### ISSUE THREAD

**Issue by soundstripe** [Synergetic-Engineering/odata-influxdb#9]
InfluxDB is very lax about checking names of dbs and measurements (see influxdb [issue#6011](https://github.com/influxdata/influxdb/issues/6011)) and we can't possibly handle all cases, but spaces are probably common so we should handle that.

**Comment by soundstripe** [comment]
#10 should fix this. Needs real-world data testing.

**Comment by srp-synengco** [comment]
Yeah, when I get a chance I'll put some data into our test environment with spaces and see how I go to test that out

**Comment by mkarlesky** [comment]
Tried out the latest with our testing instance of Influx. Definitely see some progress in that our ‘Air Temperature’ measurement is now showing up in the base feed where previously it was not. However, it seems this has flushed out a new issue. Incidentally, the connection from Power BI is still failing with the same error as previously.

Here's the server log upon starting up and connecting to Influx:
```
⚡ python server.py
INFO:odata-influxdb:Generating OData metadata xml file from InfluxDB metadata
WARNING:root:Bad attribute value for ('~', u'Name'): farmlab__Air Temperature
ERROR:root:EntitySet farmlab__Air__sp__Temperature has undeclared type: InfluxDBSchema.farmlab__Air__sp__Temperature
INFO:odata-influxdb:Starting HTTP server on port 9999...
```

And here's a snippet of the metadata. Note that ‘pH’ has an EntityType but ‘Air__sp__Temperature’ does not. I'm supposing the error in the server console log is directly related to this omission as is Power BI's complaint.
```
<EntityType Abstract="false" Name="farmlab__pH">
  <Key>
    <PropertyRef Name="time"/>
  </Key>
  <Property Name="time" Nullable="false" Type="Edm.DateTime"/>
  <Property Name="Location" Nullable="true" Type="Edm.String"/>
  <Property Name="Units" Nullable="true" Type="Edm.String"/>
  <Property Name="Test" Nullable="true" Type="Edm.String"/>
  <Property Name="Value" Nullable="true" Type="Edm.Double"/>
  <Property Name="Sensor" Nullable="true" Type="Edm.String"/>
</EntityType>
<EntityContainer m:IsDefaultEntityContainer="true" Name="InfluxDB">
  <EntitySet EntityType="InfluxDBSchema.internal__cq" Name="internal__cq"/>
  <EntitySet EntityType="InfluxDBSchema.internal__database" Name="internal__database"/>
  <EntitySet EntityType="InfluxDBSchema.internal__httpd" Name="internal__httpd"/>
  <EntitySet EntityType="InfluxDBSchema.internal__queryExecutor" Name="internal__queryExecutor"/>
  <EntitySet EntityType="InfluxDBSchema.internal__runtime" Name="internal__runtime"/>
  <EntitySet EntityType="InfluxDBSchema.internal__shard" Name="internal__shard"/>
  <EntitySet EntityType="InfluxDBSchema.internal__subscriber" Name="internal__subscriber"/>
  <EntitySet EntityType="InfluxDBSchema.internal__tsm1_cache" Name="internal__tsm1_cache"/>
  <EntitySet EntityType="InfluxDBSchema.internal__tsm1_engine" Name="internal__tsm1_engine"/>
  <EntitySet EntityType="InfluxDBSchema.internal__tsm1_filestore" Name="internal__tsm1_filestore"/>
  <EntitySet EntityType="InfluxDBSchema.internal__tsm1_wal" Name="internal__tsm1_wal"/>
  <EntitySet EntityType="InfluxDBSchema.internal__write" Name="internal__write"/>
  <EntitySet EntityType="InfluxDBSchema.farmlab__Air__sp__Temperature" Name="farmlab__Air__sp__Temperature"/>
  <EntitySet EntityType="InfluxDBSchema.farmlab__pH" Name="farmlab__pH"/>
</EntityContainer>
```

**Comment by srp-synengco** [comment]
#11 works for me but I'll let you have a go first @mkarlesky before I close this one off

**Comment by mkarlesky** [comment]
No more errors in the console log. Base feed and metadata both look good in a browser.

Oddly, Power BI reports that it's unable to connect to the server (and no traceback in the odata-influxdb console log). A browser on the same machine is able to connect fine and generates a traceback.

I'd say issue #9 is resolved, and we need to do some troubleshooting in Power BI.

**Comment by srp-synengco** [comment]
Thanks mate, will close this one

But feel free to post what you find it out to be here anyway, sounds like it could be useful to know for us / others (& of course, if it's a bug, don't hesitate to raise an issue :smile:)
